---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dmp-roadmap-db
  namespace: dmp-roadmap-dev
spec:
  encryptedData:
    DATABASE_URL: AgAVz0SvGoSYeY5XQGVpSBjU0YjG862R03sGYxXPqRfazEludyZdcKzIKBG/gV9I4LZ/mwk86bENcZ95NlIJW59RkZ3RoZCjitpAAUZHcEwyxDKKMXlPiHGj1mGA6b2tZd3MWCXblzStpwtUfDFKizv/C9DWkIsxHTbt9aRj8B3FV/GTanSnBdn8MyqxSCHAqt5hekJRE+bQ+3q42l898krHrBs9NWs+nSaYZtubbRT5uNACO4fF7/GBT5FlAa2bwJBO4CvbRQDbxxGD0TLL5dp3m8QAfhq3U/b9ISe6AbbIXhDDPJJyiscfGettCJj3tWGNiHUiNQSqAR2mjoSx0dtl/pCxkR02tLzH6npVm3qo9/DEcoZiFT1L3emiDLKO/LEZrHO3Wx4lrQ9APYI4MqgqNyTmbxZAnOeTweT4VOtJnz1oAMaUJYQWrrsUfV5Ge+uxOsuZvOUKvoJf6QZBMWnYkjm5aAgyfJH6VebiR7E5Rj64p7J7Z3s6ZGP3dIdmDk1ypGhLAJvhlZ0WRBAElj1ZYrcy9dtY2N8GFBNTS3vlyx9G6wrl9f0g4dAjiRVn2bngEQm3ga5jXZdUXk6Ak2/5N6Z3EyPPKx8choS4blVoB7PI23c888PAzE2wSK4gjNu2/kAWO83uTye7cNCYYJAFdIpSr0VSLo98JYsdyzUU+HiymUS6Z3q0AneEE5TATpqW+MQlmtkKdOq1h4BzMwMY7bfcRj4GZkr0lNE7QwpqNDOgt9PebqvFoWzd5E5JOtqV9R90NKGHfnFjuL2xUErV6m+5P2KghuZzLmGMQFamW7vK1f/TgnKYw/PMRwRbRzwk7AyZfhtbVh0yoVAJhIU/Ky+ef46ND0d/S3kiAnVgBNc9TyUa8rsUocKuiwJErbTEh4+K
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: argocd
      name: dmp-roadmap-db
      namespace: dmp-roadmap-dev
    type: Opaque
